name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:

  lint:
    name: Lint code 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      # npm install is slow and wasteful because it installs all dependencies
      # including dev dependencies, which is unnecessary for production use
      # cache the node_modules directory between runs
      # We use npm ci instead, which installs only production dependencies
      # and is much faster.
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      - name: Install dependencies
        run: npm ci

      - name: Run ESlint
        run: npx eslint . --ext .js || echo "No ESLint config found, skipping..."
    


  test:
    name: Run Tests
    uses: ./.github/workflows/reusable-test.yml
    with:
      node-version: '18'
    secrets:
      API_KEY: ${{ secrets.API_KEY }}
      NODE_ENV: test


  security-scan:
    name: Security scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm ci

      - name: Run npm audit
        run: npm audit --audit-level=moderate
        continue-on-error: ${{ github.event_name == 'pull_request' }} # true on PRs and false on push

      # check out for outdated packages
      - name: Check for outdated packages
        run: npm outdated || true




  # Build Docker Image ( depends on test passing )
  build-and-push:
    name: Build Application
    runs-on: ubuntu-latest
    needs: [lint, test, security-scan] # wait for lint and test to pass

    # only run on pushes to main not on PR requests
    if: github.ref == 'refs/heads/main'

    permissions:
      contents: read
      packages: write # Required to push to ghcr.io
      security-events: write # For uploading scan results


    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login to github registry
      - name: Login to Github container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      # Prepare image tags
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/ci-cd-github-actions
          tags: |
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}


      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=docker



      - name: Save Docker Image
        run: docker save $(echo "${{ steps.meta.outputs.tags }}" | head -n 1) -o app-image.tar

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: app-image.tar    


      # NEW: Scan the image for vulnerabilities  
      - name: Run Trivy vulnerabilitiy scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/${{ github.repository_owner }}/ci-cd-github-actions:latest'
          format: 'sarif'
          output: 'trivy-results.sarif'

      # Upload results to github security tab
      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'trivy-results.sarif'



  deploy-staging:
    name: Deploy to staging
    runs-on: ubuntu-latest
    needs: [build-and-push]

    # only run on pushes to main ( not on PRs )
    if: github.ref == 'refs/heads/feat/ssh+docker' && github.event_name == 'push'

    environment:
      name: staging
      url: http://${{ secrets.STAGING_SERVER_IP }}:3000

    

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.STAGING_SERVER_IP }} >> ~/.ssh/known_hosts


      - name: Deploy to staging
        run: |
          ssh ubuntu@${{ secrets.STAGING_SERVER_IP }} << 'EOF'

            # Login to GitHub Container Registry
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            # Pull latest image
            docker pull ghcr.io/${{ github.repository_owner }}/ci-cd-github-actions:latest
            
            # Stop old container
            docker stop ci-cd-github-actions || true
            docker rm ci-cd-github-actions || true
            
            # Run new container
            docker run -d \
              --name ci-cd-github-actions \
              --restart unless-stopped \
              -p 3000:3000 \
              -e NODE_ENV=production \
              -e API_KEY=${{ secrets.API_KEY }} \
              ghcr.io/${{ github.repository_owner }}/ci-cd-github-actions:latest
            
            # Verify it's running
            sleep 5
            curl -f http://localhost:3000/health || exit 1
          EOF


